global:
  scrap_interval: 15s
  evaluation_interval: 15s #how often rules are evaluated

rule_files: []

scrap_configs:
  - job_name: 'prometheus'
    scrap_interval: 15s
    static_configs:
      - targets:['9090']
  - job_name: 'api-server'
    metrics_path: '/metrics'
    scrap_interval: 15s
    static_configs:
      - targets:['localhost:3001']

